2021-07-08 00:26:16,443 INFO autoreload 46773 140605287601984 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/profile changed, reloading.
2021-07-08 00:26:19,054 INFO autoreload 48182 139829892642624 Watching for file changes with StatReloader
2021-07-08 00:26:22,790 WARNING log 48182 139829784761920 Not Found: /favicon.ico
2021-07-08 00:28:10,999 WARNING log 48182 139829555746368 Not Found: /favicon.ico
2021-07-08 00:51:17,701 INFO autoreload 48182 139829892642624 /run/media/dipto/DK/Projects/University/Patient-Management-System/heartcare/settings.py changed, reloading.
2021-07-08 00:51:20,173 INFO autoreload 49565 139814238127936 Watching for file changes with StatReloader
2021-07-08 00:51:29,730 INFO autoreload 49565 139814238127936 /run/media/dipto/DK/Projects/University/Patient-Management-System/heartcare/settings.py changed, reloading.
2021-07-08 00:51:32,622 INFO autoreload 49573 139749488596800 Watching for file changes with StatReloader
2021-07-08 00:56:16,523 INFO autoreload 49573 139749488596800 /run/media/dipto/DK/Projects/University/Patient-Management-System/heartcare/settings.py changed, reloading.
2021-07-08 00:56:19,742 INFO autoreload 49879 140050650187584 Watching for file changes with StatReloader
2021-07-08 01:16:31,000 INFO autoreload 49879 140050650187584 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/models/__init__.py changed, reloading.
2021-07-08 01:16:33,650 INFO autoreload 51147 140661714249536 Watching for file changes with StatReloader
2021-07-08 01:16:39,761 INFO autoreload 51147 140661714249536 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/models/__init__.py changed, reloading.
2021-07-08 01:16:41,789 INFO autoreload 51159 140409120073536 Watching for file changes with StatReloader
2021-07-08 01:17:25,321 INFO autoreload 51159 140409120073536 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/admin.py changed, reloading.
2021-07-08 01:17:27,355 INFO autoreload 51221 140611711727424 Watching for file changes with StatReloader
2021-07-08 01:17:39,413 INFO autoreload 51221 140611711727424 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/admin.py changed, reloading.
2021-07-08 01:17:41,672 INFO autoreload 51232 139742156023616 Watching for file changes with StatReloader
2021-07-08 01:17:46,668 INFO autoreload 51232 139742156023616 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/admin.py changed, reloading.
2021-07-08 01:17:48,963 INFO autoreload 51238 139881386235712 Watching for file changes with StatReloader
2021-07-08 01:17:54,079 INFO autoreload 51238 139881386235712 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/admin.py changed, reloading.
2021-07-08 01:17:55,942 INFO autoreload 51244 140221359118144 Watching for file changes with StatReloader
2021-07-08 01:18:51,135 INFO autoreload 51303 140027837224768 Watching for file changes with StatReloader
2021-07-08 01:22:25,385 INFO autoreload 51303 140027837224768 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/models/doctor_prescription.py changed, reloading.
2021-07-08 01:22:28,034 INFO autoreload 51652 140711244511040 Watching for file changes with StatReloader
2021-07-08 01:23:35,018 INFO autoreload 51652 140711244511040 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/models/doctor_prescription.py changed, reloading.
2021-07-08 01:23:37,612 INFO autoreload 51818 140386185230144 Watching for file changes with StatReloader
2021-07-08 01:23:43,275 INFO autoreload 51818 140386185230144 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/models/doctor_prescription.py changed, reloading.
2021-07-08 01:23:45,704 INFO autoreload 51824 139810487121728 Watching for file changes with StatReloader
2021-07-08 20:03:59,601 INFO autoreload 45607 139773816100672 Watching for file changes with StatReloader
2021-07-08 20:12:37,810 ERROR log 45607 139773192693312 Internal Server Error: /patient/calender/appointment/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py", line 40, in form_valid
    if save_object.serial_number > 0:
AttributeError: 'NoneType' object has no attribute 'serial_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py", line 45, in form_valid
    redirect(self.get_error_url())
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/shortcuts.py", line 122, in resolve_url
    to = str(to)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
2021-07-08 20:12:38,269 WARNING log 45607 139773192693312 Not Found: /favicon.ico
2021-07-08 20:13:00,935 ERROR log 45607 139773192693312 Internal Server Error: /patient/calender/appointment/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py", line 40, in form_valid
    if save_object.serial_number > 0:
AttributeError: 'NoneType' object has no attribute 'serial_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py", line 45, in form_valid
    redirect(self.get_error_url())
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/shortcuts.py", line 122, in resolve_url
    to = str(to)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
2021-07-08 20:13:27,847 WARNING log 45607 139773728679488 Not Found: /manage/
2021-07-08 20:18:25,145 ERROR log 45607 139773192693312 Internal Server Error: /patient/calender/appointment/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py", line 40, in form_valid
    if save_object.serial_number > 0:
AttributeError: 'NoneType' object has no attribute 'serial_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py", line 45, in form_valid
    redirect(self.get_error_url())
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/shortcuts.py", line 122, in resolve_url
    to = str(to)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/utils/functional.py", line 140, in __text_cast
    return func(*self.__args, **self.__kw)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
2021-07-08 20:19:47,885 INFO autoreload 45607 139773816100672 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py changed, reloading.
2021-07-08 20:19:50,977 INFO autoreload 46751 139929233790784 Watching for file changes with StatReloader
2021-07-08 20:19:56,641 INFO autoreload 46751 139929233790784 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/doctor_appoiment.py changed, reloading.
2021-07-08 20:19:59,777 INFO autoreload 46764 140064146085696 Watching for file changes with StatReloader
2021-07-08 21:05:08,393 INFO autoreload 46764 140064146085696 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/forms/__init__.py changed, reloading.
2021-07-08 21:05:10,878 INFO autoreload 49416 140421942130496 Watching for file changes with StatReloader
2021-07-08 21:05:15,684 INFO autoreload 49416 140421942130496 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/forms/__init__.py changed, reloading.
2021-07-08 21:05:17,694 INFO autoreload 49427 139623020828480 Watching for file changes with StatReloader
2021-07-08 23:01:45,304 INFO autoreload 49427 139623020828480 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard changed, reloading.
2021-07-08 23:01:47,888 INFO autoreload 53412 140627488433984 Watching for file changes with StatReloader
2021-07-08 23:02:12,590 INFO autoreload 53412 140627488433984 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/record changed, reloading.
2021-07-08 23:02:15,491 INFO autoreload 53442 139696700675904 Watching for file changes with StatReloader
2021-07-08 23:11:51,574 INFO autoreload 53442 139696700675904 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/__init__.py changed, reloading.
2021-07-08 23:11:53,552 INFO autoreload 53791 140072112924480 Watching for file changes with StatReloader
2021-07-08 23:20:31,937 INFO autoreload 53791 140072112924480 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/urls.py changed, reloading.
2021-07-08 23:20:33,912 INFO autoreload 54121 139639866816320 Watching for file changes with StatReloader
2021-07-08 23:20:43,485 INFO autoreload 54121 139639866816320 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/urls.py changed, reloading.
2021-07-08 23:20:45,581 INFO autoreload 54133 140062536464192 Watching for file changes with StatReloader
2021-07-08 23:23:22,506 INFO autoreload 54133 140062536464192 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/urls.py changed, reloading.
2021-07-08 23:23:24,504 INFO autoreload 54239 140379124488000 Watching for file changes with StatReloader
2021-07-08 23:25:07,117 INFO autoreload 54239 140379124488000 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/urls.py changed, reloading.
2021-07-08 23:25:09,294 INFO autoreload 54312 140606999254848 Watching for file changes with StatReloader
2021-07-08 23:38:30,533 INFO autoreload 54312 140606999254848 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/appointment changed, reloading.
2021-07-08 23:38:32,650 INFO autoreload 54716 140021431727936 Watching for file changes with StatReloader
2021-07-08 23:38:55,328 INFO autoreload 54716 140021431727936 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/appointment changed, reloading.
2021-07-08 23:38:57,361 INFO autoreload 54728 139841010440000 Watching for file changes with StatReloader
2021-07-08 23:39:07,907 INFO autoreload 54728 139841010440000 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/appointment changed, reloading.
2021-07-08 23:39:10,064 INFO autoreload 54734 139874832242496 Watching for file changes with StatReloader
2021-07-08 23:39:19,312 INFO autoreload 54734 139874832242496 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/appointment changed, reloading.
2021-07-08 23:39:21,664 INFO autoreload 54741 139902230173504 Watching for file changes with StatReloader
2021-07-08 23:39:32,392 ERROR log 54741 139902143538752 Internal Server Error: /patient/patient/25/add/record/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2021-07-08 23:40:57,932 INFO autoreload 54741 139902230173504 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/appointment changed, reloading.
2021-07-08 23:41:00,136 INFO autoreload 54844 140448989607744 Watching for file changes with StatReloader
2021-07-08 23:41:09,229 ERROR log 54844 140448902186560 Internal Server Error: /uncheck/appointment/list/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/defaulttags.py", line 965, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/defaulttags.py", line 1389, in url
    args.append(parser.compile_filter(value))
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=' from 'pk='
2021-07-08 23:41:30,682 INFO autoreload 54844 140448989607744 /run/media/dipto/DK/Projects/University/Patient-Management-System/templates/dashboard/appointment changed, reloading.
2021-07-08 23:41:32,859 INFO autoreload 54875 139658395936576 Watching for file changes with StatReloader
2021-07-08 23:41:44,251 ERROR log 54875 139658242164288 Internal Server Error: /patient/patient/2/add/record/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2021-07-08 23:42:45,510 INFO autoreload 54875 139658395936576 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:42:47,958 INFO autoreload 54944 139930631681856 Watching for file changes with StatReloader
2021-07-08 23:42:54,615 INFO autoreload 54944 139930631681856 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:42:56,595 INFO autoreload 54954 140406654203712 Watching for file changes with StatReloader
2021-07-08 23:43:00,818 ERROR log 54954 140406567306816 Internal Server Error: /patient/patient/2/add/record/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2021-07-08 23:43:21,861 INFO autoreload 54954 140406654203712 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:43:24,025 INFO autoreload 54993 140527895398208 Watching for file changes with StatReloader
2021-07-08 23:43:44,969 INFO autoreload 54993 140527895398208 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:43:47,222 INFO autoreload 55018 140673009772352 Watching for file changes with StatReloader
2021-07-08 23:43:48,358 ERROR log 55018 140672923924032 Internal Server Error: /patient/patient/2/add/record/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2021-07-08 23:43:50,455 ERROR log 55018 140672923924032 Internal Server Error: /patient/patient/2/add/record/
Traceback (most recent call last):
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/run/media/dipto/DK/Projects/University/Patient-Management-System/dj/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
2021-07-08 23:44:34,921 INFO autoreload 55018 140673009772352 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:44:37,241 INFO autoreload 55159 139791491827520 Watching for file changes with StatReloader
2021-07-08 23:44:43,338 INFO autoreload 55159 139791491827520 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:44:45,464 INFO autoreload 55168 140125346895680 Watching for file changes with StatReloader
2021-07-08 23:45:51,619 INFO autoreload 55168 140125346895680 /run/media/dipto/DK/Projects/University/Patient-Management-System/patient_ms/views/add_record.py changed, reloading.
2021-07-08 23:45:54,281 INFO autoreload 55245 140508054468416 Watching for file changes with StatReloader
